### ISSUE TITLE
Double quotes missing in ccflags (perl-5.22.0)

### ISSUE THREAD

**Issue by kasparh** [gugod/App-perlbrew#466]
Hi,

When I install perl-5.22.0 as follows, things work just fine:

$ perlbrew install perl-5.22.0

However, I would like to add the following directory to the the @INC array:

/usr/local/lib/perl5

For previous perl 5 versions I did this like so:

$ perlbrew install -Accflags='-DAPPLLIB_EXP=\"/usr/local/lib/perl5\"' perl-5.18.4

And that worked just fine, but doesn't work with perl-5.22.0.

It looks like the double  quotation marks get removed. This then causes a compilation error (see below).

Your help is much appreciated!

Thank you!

Excerpt of log file:

./miniperl -Ilib -Ilib -MExtUtils::Miniperl -e 'writemain(\"perlmain.c", @ARGV)' DynaLoader 
cc -c -DPERL_CORE -fno-common -DPERL_DARWIN -DAPPLLIB_EXP=/usr/local/lib/perl5 -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -std=c89 -O3 -Wall -Werror=declaration-after-statement -Wextra -Wc++-compat -Wwrite-strings perlmain.c
cc -c -DPERL_CORE -fno-common -DPERL_DARWIN -DAPPLLIB_EXP=/usr/local/lib/perl5 -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -std=c89 -O3 -Wall -Werror=declaration-after-statement -Wextra -Wc++-compat -Wwrite-strings op.c
cc -c -DPERL_CORE -fno-common -DPERL_DARWIN -DAPPLLIB_EXP=/usr/local/lib/perl5 -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -std=c89 -O3 -Wall -Werror=declaration-after-statement -Wextra -Wc++-compat -Wwrite-strings perl.c
perl.c: In function 'S_init_perllib':
perl.c:4372: error: 'usr' undeclared (first use in this function)
perl.c:4372: error: (Each undeclared identifier is reported only once
perl.c:4372: error: for each function it appears in.)
perl.c:4372: error: 'local' undeclared (first use in this function)
perl.c:4372: error: 'lib' undeclared (first use in this function)
perl.c:4372: error: 'perl5' undeclared (first use in this function)
perl.c:4372: error: expected ')' before string constant
perl.c:4372: error: expected expression before '/' token
perl.c:4476: error: expected ')' before string constant
perl.c:4476: error: expected expression before '/' token
make: *** [perl.o] Error 1

**Comment by geraldlai** [comment]
This is a perl-5.22.0 bug mentioned at: https://rt.perl.org/Public/Bug/Display.html?id=125314

As mentioned, [57d2761b46edd92efa00f984cb9840506d3b6483](http://www.nntp.perl.org/group/perl.perl5.changes/2014/06/msg41057.html) is the first bad commit.

Removing $myccflags from cflags.SH is a workaround:

```
--- cflags.SH
+++ cflags.SH
@@ -17,7 +17,6 @@
 #
 # From this we initialise the following variables in the cflags script:
 #
-#   $myccflags (possibly edited version of $Config{ccflags})
 #   $warn
 #   $stdflags
 #   $extra
@@ -401,7 +400,6 @@
 # This file is generated by cflags.SH
 
 # Used to restore possible edits by cflags.SH.
-myccflags="$ccflags"
 # Extra warnings, used e.g. for gcc.
 warn="$warn"
 # Extra standardness.
@@ -426,7 +424,6 @@
                echo "Can't find config.sh."; exit 1
        fi
        . $TOP/config.sh
-        ccflags="$myccflags"  # Restore possible edits by cflags.SH.
        ;;
 esac
```

**Comment by jhi** [comment]
Please try the suggested patch at https://rt.perl.org/Ticket/Display.html?id=125314

**Comment by kasparh** [comment]
Thanks! This worked like  dream.
